# Generated by Django 5.0.5 on 2024-05-09 14:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('retail', '0002_trader_products'),
    ]

    operations = [
        migrations.AddField(
            model_name='network',
            name='trader',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='retail.trader', verbose_name='Продавец'),
        ),
    ]
