# Generated by Django 5.0.5 on 2024-05-11 16:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('retail', '0003_network_trader'),
    ]

    operations = [
        migrations.AddField(
            model_name='network',
            name='factory',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='factory', to='retail.trader', verbose_name='Производитель'),
        ),
        migrations.AddField(
            model_name='network',
            name='provider',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='provider', to='retail.trader', verbose_name='Поставщик'),
        ),
        migrations.AlterField(
            model_name='network',
            name='trader',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='trade', to='retail.trader', verbose_name='Продавец'),
        ),
    ]
